version: '2' #https://docs.docker.com/compose/compose-file/#/version-2
services:
  app:
    build:
      context: ../
      dockerfile: ../godocker/Dockerfile
      args:
        APP_FOLDER: ../godocker/sample-app
    volumes:
      - ../godocker/sample-app:/go/src/app #for sync of files so fresh rebuilds
    ports:
      - 8080:8080
    environment:
      - PORT=8080 #app listen to it
