version: '2' #https://docs.docker.com/compose/compose-file/#/version-2
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/go/src/app #for sync of files so gin rebuilds
    ports:
      - 3000:3000
