version: '2' #https://docs.docker.com/compose/compose-file/#/version-2
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_FOLDER: ./app
    volumes:
      - ./app:/go/src/app #for sync of files so gin rebuilds
    ports:
      - 3000:3000
    environment:
      - PORT=3001 #gin forwards to 3001 app listen to it
